### PR TITLE
Run Stan models (normal mixture)

### PR DESCRIPTION
**Pull request by xukai92**
Run the normal mixture model in Stan.

The script seems to work.

NOTE: I guess the build filed written by Stan.jl team is problematic itself. We don't necessary need to "build Stan.jl successfully" to use Stan.jl. From the log we can see the Stan model is successfully built and run, even we didn't build the Stan.jl successfully. This happens to my local Linux machine as well.

### CODE REVIEW

**Comment by yebai** [comment]
Do we actually need to build Stan.jl?

**Comment by xukai92** [comment]
We don't need to build it explicitly because when we call `Pkg.add("Stan")` it actually builds Stan.jl. I will remove `Pkg.build("Stan")`.

**Comment by xukai92** [comment]
I think the script for bench works now. I'm gonna add Stan version of bernoulli and simplegauss now.

**Comment by yebai** [comment]
It might be useful to compute and print the difference (e.g. mean, variance) between Stan and Turing

**Comment by xukai92** [comment]
Yeah. That makes a lot of sense. Will do!

**Pull request merged**
