### PR TITLE
Initialised readthedoc folder

### PR DESCRIPTION
**Pull request by xukai92**

### CODE REVIEW

**Comment by yebai** [comment]
@xukai92 Many thanks!
@evsmithx Could you review Kai's code? Ideally, we can have a doc web that looks like [this one](https://julia.readthedocs.io/en/release-0.4/) - the template can be found [here](https://github.com/JuliaLang/JuliaDoc).

**Comment by evsmithx** [comment]
I've added the JuliaDoc theme; the results can be seen here: http://turingjl-docs.readthedocs.io/en/docs/.

**Comment by yebai** [comment]
@xukai92 I've merged this PR. Could you re-configure `http://turingjl.readthedocs.io/en/latest/` to pull doc source from our main repo?

**Comment by xukai92** [comment]
@yebai There seems to be some login problems from [readthedocs.io](readthedocs.io) now. I cannot login [readthedocs.io](readthedocs.io) with my account. I will try it a bit later.

**Comment by xukai92** [comment]
@yebai I've re-configured it. It's available at http://turingjl.readthedocs.io/ now.

**Pull request merged**
