### PR TITLE
Improve benchmark

### PR DESCRIPTION
**Pull request by yebai**
Kai: this PR was "Support explicit return statement #132" but #132 was decided to postponed to later release due to some difficulties we meet.

### CODE REVIEW

**Comment by yebai** [comment]
@xukai92 There is a small issue for supporting explicit return statements. I have documented the issue in #323. It should be OK to merge this PR now as we can probably fix #323 later.

**Comment by xukai92** [comment]
Do you think it might be better to just store them in `spl.info`?

**Comment by yebai** [comment]
> Do you think it might be better to just store them in spl.info?

We want to be able to run the program without any samplers, so it's better to keep model function independent of sampler specific data structures. But as an alternative, we could modify the compiler so that model functions return `(v::VarInfo, s::Union{Void, Sample}` instead of `v::VarInfo` if needed.

**Comment by xukai92** [comment]
I would prefer to return the tuple instead of putting things into `VarInfo`. What I am concerned is that the putting return samples will be carried with `VarInfo`, which may slow unnecessarily down the whole sampling?

Maybe we can also do things differently depending on if `sampler` is `nothing` - do nothing for return statement if sampler is missing and update them in sampler if it exists. In this way we always return vi still.

**Comment by yebai** [comment]
> I would prefer to return the tuple instead of putting things into VarInfo. What I am concerned is that the putting return samples will be carried with VarInfo, which may slow unnecessarily down the whole sampling?

Let's go for a tuple for #323

**Comment by xukai92** [comment]
I haven't make it to update the value yet

**Comment by yebai** [comment]
> I haven't make it to update the value yet

That's OK. I will merge this PR when you are done.

**Comment by xukai92** [comment]
I realise that my implementation actually has a bug where it doesn't handle coroutines correctly.

**Comment by xukai92** [comment]
Regarding the corountine issue, I ended up adding a new filed to VarInfo, for the following reason:
1. We need store "predictions" in corountine level. There are many ways to do, e.g. what we did before is using task.storage. We can also add fields to particles but I choose to bind that to VarInfo for consistence.
2. Adding a new filed to VarInfo makes it easy to drop the predictions after each vi -> sample conversion, so that we don't waste time to copy them in the future.
  - This currently gives me error and need to be fixed. I disable the empty now.

**Comment by yebai** [comment]
>Adding a new filed to VarInfo makes it easy to drop the predictions after each vi -> sample conversion, so that we don't waste time to copy them in the future.

Adding a `pred` field to `VarInfo` sounds good!

**Comment by xukai92** [comment]
The update of `pred` into sample is on L67 in `helper.jl`. I was trying to reset `pred` after each conversion, but it gives me error when wrapping samples into `Chain` (seems for PG only). I put comments from L73 to L79. Can you have a look at it?

**Comment by xukai92** [comment]
Another bug of explicit return:

When HMC dealing with numerical overflow, it only recovers the theta but not the vi.pred used by last numerical OK run of model.

**Comment by yebai** [comment]
Note: I merged the part fixing #264 of this PR into the master branch.

**Comment by yebai** [comment]
@xukai92 Yes, let's do that and merge this PR.

**Comment by xukai92** [comment]
@yebai I've disabled the explicit return. Can you review this PR and accept it if everything is fine?

**Pull request merged**
