### PR TITLE
Improve bench log

### PR DESCRIPTION
**Pull request by xukai92**
Resolve https://github.com/yebai/Turing.jl/issues/151

### CODE REVIEW

**Comment by yebai** [comment]
This looks good. 
BTW, is it possible to get the running time for Stan as well? This would be helpful for us to get a sense of the performance difference between Stan and Turing (say drawing equal numbers of HMC/NUTS samplers).

**Comment by xukai92** [comment]
I looked into that yesterday but it seems that Stan.jl doesn't store time in the Chain. Alternatively I can call `@elapsed` on the call for Stan but it will include the compile time as well.

**Comment by xukai92** [comment]
- [ ] Improve Simple Gaussian Mixture
- [ ] Get Stan time from .csv

**Comment by xukai92** [comment]
@yebai I think this PR is ready to be merged. Can you please have a look?

**Comment by xukai92** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated.
It seems that we can't run the benchmark script as long as we want.

**Comment by yebai** [comment]
> There is no timeout for a build; a build will run as long as all the jobs do as long as each job does not timeout.

https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts

I think we might need to print something every 10 mins in order to keep the job alive.

**Comment by xukai92** [comment]
Yes, I've encountered this problem and already done that, i.e. make PG prints progress.

I think our benchmark script did last for 50 mins and got stopped by Travis.

**Comment by xukai92** [comment]
Just checked that the script was stopped after "Ran for 49 min 58 sec"

**Pull request merged**
