### PR TITLE
Unify rand interface

### PR DESCRIPTION
**Pull request by xukai92**
Resolves https://github.com/yebai/Turing.jl/issues/123

### CODE REVIEW

**Comment by yebai** [comment]
@xukai92 It is probably better to have a few additional tests that can check `randrn` and `VarInfo`, for example

- try to override existing entries in `VarInfo` should return warning or error. (In the case of error, we can add an additional parameter `forceOverride` to `randrn`, and only allow overriding when `forceOverride` is set to true).

- Test whether values stored in `VarInfo` are identical with original copies.

**Comment by xukai92** [comment]
- `randrn()` itself doesn't overwrite the content of `VarInfo`. It only either add a new entry or replay an existing one. 
  - The function HMC uses to change the values in `VarInfo` during its steps is `setval()`. I've added a `overwrite` parameter to `setval()`, with its default value being `false`. 
  - I think give warnings to each overwriting operation is not good as HMC overwrites values in `VarInfo` quite frequently. 
    - I tried adding warning to each overwriting operation and there are too many warnings. 
    - I ended up giving warning messages to `setval()` when users use it without setting `overwrite` to be true. 
- I don't get the second bullet point.
- I can fix #129 in this PR. Will do it soon.
- I believe I put the wrong test for the Gaussian model in benchmark. I've update it.

**Comment by yebai** [comment]
> I don't get the second bullet point: "Test whether values stored in VarInfo are identical with original copies."

Can we add the following test

```julia

# Create a variable and store it in vi
vn  = ... # some variable name
x = randrc(vi, dist, vn, spl)

# Then, test whether vi[vn] == x;

```

Ideally, we should test univariate, vector variate, and matrix variate distributions.

**Comment by xukai92** [comment]
Can we merge this PR?

**Comment by yebai** [comment]
Seems that benchmarking is still broken: https://travis-ci.org/yebai/Turing.jl/jobs/217986302

**Comment by xukai92** [comment]
I see. As we abandon the use original Julia type. We cannot get `:y` now but only `Symbol("y[1]")`  and `Symbol("y[2]")`. I will fix it now.

**Pull request merged**
