### PR TITLE
Changes we made and models used in NIPS 2017

### PR DESCRIPTION
**Pull request by xukai92**
Models added
- SV (Stan version)
  - Also comes with a script to generate data
  - Also comes with the 4 data-sets we used
- GMM (gen)
- HMM (discrete observations)
  - Also comes with a script to generate data

Features
- Pre-conditioning (#67) added
- Fix some IO bugs for un-thinned Gibbs
- Use `randcat` in PG
  - Will we keep this?

### CODE REVIEW

**Comment by yebai** [comment]
@xukai92 
Seems both tests are failing. Could we fix that?

> Use randcat in PG Will we keep this?
It's OK to keep it for now. I'll fix this.

**Comment by yebai** [comment]
@xukai92 Could we create a jupyter notebook that can reproduce the `gmm` experiment?

**Comment by xukai92** [comment]
Sure. Will do it tonight.

**Comment by xukai92** [comment]
Unsure why Cairo has build error on Win32

**Comment by yebai** [comment]
@xukai92 
The GMM histogram plots for NUTS, Gibbs and Exact is overlapping with each other, could we do the same trick as in the NIPS draft?

@xukai92 
The FHMM model seems broken.

**Comment by xukai92** [comment]
@yebai 
1. Sure.
2. We don't have a FHMM model in the repo. Do you mean the HMM with discrete observation in the `nips-2017` path?

**Comment by xukai92** [comment]
AppVeyor fails because of numerical error. I guess it's fine and can you please review the PR @yebai

**Comment by yebai** [comment]
@xukai92 
No problem!

**Pull request merged**
