### PR TITLE
Remove functions exports from Mamba

### PR DESCRIPTION
**Pull request by xukai92**
Addressing https://github.com/yebai/Turing.jl/issues/155

### CODE REVIEW

**Comment by xukai92** [comment]
@yebai The AppVeyor is back after `using Mamba` is removed!

**Comment by yebai** [comment]
That’s cool. Perhaps some Mamba dependency is broken on Appveyor, but why using a different import mechanism would solve the problem?

**Comment by xukai92** [comment]
I'm not sure. My guess is that Mamba itself exports some functions which causes conflicts to others. Instead of call `using Mamba` but only `import Mamba: Chains, Abstract Chains` is called, other exports from Mamba will not make influence?

**Comment by xukai92** [comment]
BTW it seems that still I cannot restart or do things to Appveyor build?

**Pull request merged**
