### PR TITLE
NUTS without Dual Averaging (Algorithm 3 of the NUTS paper)

### PR DESCRIPTION
**Pull request by xukai92**
Address #193

### CODE REVIEW

**Comment by xukai92** [comment]
Efficient NUTS also seems to suffer from the similar numerical problem in #182.

**Comment by yebai** [comment]
> Efficient NUTS also seems to suffer from the similar numerical problem in #182.

I've finished the new numerical transform; need to cleanup the interface. Should be ready later today.

**Comment by xukai92** [comment]
Cool! I guess I can finish NUTS if this efficient NUTS has no problem cause I have both No-U-Turn and Dual Averaging now.

**Comment by xukai92** [comment]
The simple geweke test (a simpler Gaussian model with only unknown mean) for the sampler seems to be passed.

**Comment by xukai92** [comment]
I will make NUTS PR directly.

**Pull request closed without merging**
