### PR TITLE
Modularize AD

### PR DESCRIPTION
**Pull request by xukai92**
This PR 
1. splits AD from HMC and makes it an individual function
2. add an new abstract for gradient-based sampler `GradientSampler`.

### CODE REVIEW

**Comment by xukai92** [comment]
Following our discussion just now, there is no problem in the 2nd and 3rd bullet point. However, in AD, after consuming the model, we need to use the log-joint, which is bound with the sampler as well. 

I can come up with a (temporary) solution without changing a lot of things: we create a wrapper for logjoint and pass logjoint by reference to `get_gradient_dict`. Then everything inside it keeps the same.

However, this let me feel unhappy because we actually pass three attributes of `spl` to `get_gradient_dict` by reference. I kind of hope our model will return the logjoint by default. Maybe we also need to consider this in #55 .

**Comment by xukai92** [comment]
@yebai I've done the requested changes.

**Comment by yebai** [comment]
> However, this let me feel unhappy because we actually pass three attributes of spl to get_gradient_dict by reference. I kind of hope our model will return the logjoint by default. Maybe we also need to consider this in #55 .

Can we make `logjoint` a field of `GradientInfo`? 

Also, maybe merge `replay.jl` into `ad.jl`?

**Comment by yebai** [comment]
PS. I just looked at `replay.jl`, it seems `replay.jl` too large to be merged into `ad.jl`. Maybe we can keep it separate for now.

**Comment by xukai92** [comment]
> Can we make `logjoint` a field of `GradientInfo`?

No problem. I think it's just a decision problem. We can simply do this by amending each get/set of `spl.logjoint` to `priors.logjoint`. But I kind of fell `logjoint` itself, as an attribute, does not belong to `priors`. But I feel its better to change it as the way you proposed now & will do.

> Also, maybe merge `replay.jl` into `ad.jl`?
> PS. I just looked at `replay.jl`, it seems `replay.jl` too large to be merged into `ad.jl`. Maybe we can keep it separate for now.

I guess we can first rename it to `gradientinfo.jl` and put it to core, because I fell it should exist in the same place as `container.jl`.

**Comment by yebai** [comment]
Cool - can you push the proposed changes before I merge this PR

**Comment by xukai92** [comment]
Done!

**Pull request merged**
